name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-test:
    name: Build and Test
    runs-on: macos-latest
    env:
      DEVELOPER_DIR: /Applications/Xcode_12.app/Contents/Developer

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: .build
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-

      - name: Resolve Swift Packages
        run: swift package resolve

      - name: Lint
        run: swift run swiftlint

      - name: Build
        run: swift build --build-tests

      - name: Run tests
        run: swift test --enable-code-coverage
