name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    name: Build and Test
    runs-on: macos-latest
    env:
        DEVELOPER_DIR: /Applications/Xcode_12.app/Contents/Developer
    steps:
    - uses: actions/checkout@v2
    - name: Install homebrew dependencies
      run: brew bundle
    - name: Lint
      run: swiftlint
    - name: Build
      run: swift build
    - name: Run tests
      run: swift test
